logging:
  level:
#    org.springframework: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE

#spring:
#  datasource:
#    url: jdbc:h2:mem:testdb

spring:
  datasource:
    url: jdbc:${DATABASE_URL:mysql://usr:User12345@localhost:3306/development}
#    url: jdbc:mysql://${MYSQL_HOST:localhost}:3304/development
#    username: usr
#    password: User12345

server:
  port: 4000